# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XnLxKPy13T9oFwaWLCLQN0foPVnHqofR
"""

!pip install streamlit pyngrok

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# # paste full code here
# import streamlit as st
# import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt
# import seaborn as sns
# 
# st.set_page_config(page_title="Bank Data Analysis", layout="wide")
# 
# st.title("🏦 Bank Data Analysis Dashboard")
# 
# # Upload CSV
# uploaded_file = st.file_uploader("Upload Bank Dataset", type=["csv"])
# 
# if uploaded_file is not None:
#     df = pd.read_csv(uploaded_file)
# 
#     # ---------------------------
#     # DATA OVERVIEW
#     # ---------------------------
#     st.subheader("📊 Dataset Preview")
#     st.dataframe(df.head())
# 
#     st.subheader("📌 Dataset Summary")
#     col1, col2 = st.columns(2)
# 
#     with col1:
#         st.write("Shape of dataset:", df.shape)
#         st.write("Columns:", list(df.columns))
# 
#     with col2:
#         st.write("Data Types")
#         st.write(df.dtypes)
# 
#     # ---------------------------
#     # DATA CLEANING (as notebook)
#     # ---------------------------
#     st.subheader("🧹 Data Cleaning")
# 
#     if 'gender' in df.columns:
#         df['gender'] = df['gender'].fillna('Unknown')
# 
#     if 'dependents' in df.columns:
#         df['dependents'] = df['dependents'].fillna(0)
# 
#     if 'occupation' in df.columns:
#         df['occupation'] = df['occupation'].fillna('Unknown')
# 
#     if 'city' in df.columns:
#         df['city'] = df['city'].fillna(df['city'].mode()[0])
# 
#     st.success("Missing values handled successfully")
# 
#     # ---------------------------
#     # SIDEBAR FILTERS
#     # ---------------------------
#     st.sidebar.header("🔍 Filters")
# 
#     filtered_df = df.copy()
# 
#     if 'gender' in df.columns:
#         gender = st.sidebar.multiselect("Select Gender", df['gender'].unique(), default=df['gender'].unique())
#         filtered_df = filtered_df[filtered_df['gender'].isin(gender)]
# 
#     if 'city' in df.columns:
#         city = st.sidebar.multiselect("Select City", df['city'].unique(), default=df['city'].unique())
#         filtered_df = filtered_df[filtered_df['city'].isin(city)]
# 
#     st.subheader("📊 Filtered Data")
#     st.dataframe(filtered_df.head())
# 
#     # ---------------------------
#     # VISUALIZATIONS
#     # ---------------------------
#     st.subheader("📈 Data Visualizations")
# 
#     col1, col2 = st.columns(2)
# 
#     # Gender Count
#     if 'gender' in filtered_df.columns:
#         with col1:
#             st.write("Gender Distribution")
#             fig, ax = plt.subplots()
#             sns.countplot(x='gender', data=filtered_df, ax=ax)
#             st.pyplot(fig)
# 
#     # Churn Count (if exists)
#     if 'churn' in filtered_df.columns:
#         with col2:
#             st.write("Churn Distribution")
#             fig, ax = plt.subplots()
#             sns.countplot(x='churn', data=filtered_df, ax=ax)
#             st.pyplot(fig)
# 
#     # Balance Distribution
#     if 'balance' in filtered_df.columns:
#         st.write("Balance Distribution")
#         fig, ax = plt.subplots()
#         sns.histplot(filtered_df['balance'], kde=True, ax=ax)
#         st.pyplot(fig)
# 
#     # Age Distribution
#     if 'age' in filtered_df.columns:
#         st.write("Age Distribution")
#         fig, ax = plt.subplots()
#         sns.histplot(filtered_df['age'], kde=True, ax=ax)
#         st.pyplot(fig)
# 
#     # ---------------------------
#     # CORRELATION HEATMAP
#     # ---------------------------
#     st.subheader("🔥 Correlation Heatmap")
# 
#     numeric_df = filtered_df.select_dtypes(include=np.number)
# 
#     if not numeric_df.empty:
#         fig, ax = plt.subplots(figsize=(10, 6))
#         sns.heatmap(numeric_df.corr(), annot=True, cmap="coolwarm", ax=ax)
#         st.pyplot(fig)
#     else:
#         st.warning("No numeric columns found for correlation")
# 
#     # ---------------------------
#     # DOWNLOAD FILTERED DATA
#     # ---------------------------
#     st.subheader("⬇️ Download Filtered Data")
# 
#     csv = filtered_df.to_csv(index=False).encode('utf-8')
#     st.download_button("Download CSV", csv, "filtered_data.csv", "text/csv")
# 
# else:
#     st.info("👆 Please upload your bank dataset to begin")

